#https://wiki-ebabel.herokuapp.com/index.php?title=Vagrant-nodejs-angularjs-tutorial

Vagrant::Config.run do |config|
 
   config.vm.define "nodejs" do |nodejs|
     nodejs.vm.box = "ubuntu/xenial64"
     nodejs.vm.forward_port 8000, 4567
     nodejs.vm.host_name = "nodejs"
     nodejs.vm.provision :shell, :path => "provision.sh"
   end
 
 end