<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page buffer="none" session="false" trimDirectiveWhitespaces="true" %>

<%--
FILTER CATEGORY
-----------

"id": "${value.Id}-filter-${status.count}"
,"count": ${status.count}
,"type": "TextFilter"
<c:if test="${elem.value.Label.isSet}">,"label": "${elem.value.Label}"</c:if>
<c:if test="${elem.value.Placeholder.isSet}">,"placeholder": "${elem.value.Placeholder}"</c:if>
,"solr": "${elem.value.FieldSolr}"
,"isPrincipal": false
,"class": "${filtercssclass}"
,"value": ""
--%>

<div :class="'form-group filter filter-cat ' + filter.class" :id="'filter-' + filter.count"
     v-if="filter.type == 'CategoryFilter'">
    <label :for="filter.id"
           v-if="filter.label">{{filter.label}}</label>
    <label :for="filter.id" class="sr-only"
           v-else>{{filter.id}}</label>

    <%--SELECT--%>
    <div class="block-drop">
        <select class="form-control" :name="filter.id" :id="filter.id"
                v-model="filter.value">
            <option disabled value="" class="nivel-0"
                    v-if="filter.showEmptyOption"></option>
            <option v-for="category in filter.categories"
                    :value="category.value" :class="category.class">{{category.title}}</option>
        </select>
    </div>
    <%--</c:when>
    <c:when test="${elem.value.FieldType == 'selectmultiple' }">
        <div class="block-drop">
            <select class="form-control" name="${fieldName}" id="${fieldName}"
                    multiple>
                <%
                    String
                    [
                    ]
                    fieldValuesArray
                    =
                    request
                    .
                    getParameterValues
                    (
                    fieldName
                    )
                    ;
                    List
                    <
                    String
                    >
                    fieldValues
                    =
                    null
                    ;
                    String
                    categoryProperty
                    =
                    (
                    String
                    )
                    request
                    .
                    getAttribute
                    (
                    "filtercategoryProperty"
                    )
                    ;

                    if
                    (
                    fieldValuesArray
                    !=
                    null
                    )
                    fieldValues
                    =
                    Arrays
                    .
                    asList
                    (
                    fieldValuesArray
                    )
                    ;
                    // si nos llega el parametro vacio guardamos la propiedad de categoria definida (si es que existe) como fieldvalue para que se muestre seleccionada
                    else
                    if
                    (
                    !
                    StringUtils
                    .
                    isBlank
                    (
                    categoryProperty
                    )
                    )
                    {
                    fieldValues
                    =
                    new
                    ArrayList
                    <
                    String
                    >
                    (
                    )
                    ;
                    fieldValues
                    .
                    add
                    (
                    categoryProperty
                    )
                    ;
                    }
                    else
                    fieldValues
                    =
                    new
                    ArrayList
                    <
                    String
                    >
                    (
                    )
                    ;
                    if
                    (
                    tituloCatPadre
                    !=
                    null
                    )
                    {
                    if
                    (
                    fieldValues
                    .
                    contains
                    (
                    categoryRoot
                    )
                    )
                    out
                    .
                    println
                    (
                    "<option value=\""
                    +
                    categoryRoot
                    +
                    "\" selected=\"selected\">"
                    +
                    tituloCatPadre
                    +
                    "</option>"
                    )
                    ;
                    else
                    out
                    .
                    println
                    (
                    "<option value=\""
                    +
                    categoryRoot
                    +
                    "\">"
                    +
                    tituloCatPadre
                    +
                    "</option>"
                    )
                    ;
                    }
                    for
                    (
                    CmsCategory
                    cat
                    :
                    categorias
                    )
                    {
                    String
                    titleCat
                    =
                    ""
                    ;
                    //Primero intentamos leer la categoria Title_LOCALE, si no nos quedamos con el Title
                    try
                    {
                    String
                    site
                    =
                    OpenCms
                    .
                    getSiteManager
                    (
                    )
                    .
                    getCurrentSite
                    (
                    cmso
                    )
                    .
                    getSiteRoot
                    (
                    )
                    ;
                    String
                    pathResourceCat
                    =
                    cat
                    .
                    getRootPath
                    (
                    )
                    ;
                    pathResourceCat
                    =
                    pathResourceCat
                    .
                    replace
                    (
                    site
                    ,
                    ""
                    )
                    ;
                    titleCat
                    =
                    cmso
                    .
                    readPropertyObject
                    (
                    pathResourceCat
                    ,
                    "Title_"
                    +
                    cmso
                    .
                    getRequestContext
                    (
                    )
                    .
                    getLocale
                    (
                    )
                    ,
                    false
                    )
                    .
                    getValue
                    (
                    cat
                    .
                    getTitle
                    (
                    )
                    )
                    ;
                    }
                    catch
                    (
                    CmsException
                    ex
                    )
                    {
                    titleCat
                    =
                    cat
                    .
                    getTitle
                    (
                    )
                    ;
                    }
                    if
                    (
                    fieldValues
                    .
                    contains
                    (
                    cat
                    .
                    getPath
                    (
                    )
                    )
                    )
                    out
                    .
                    println
                    (
                    "<option value=\""
                    +
                    cat
                    .
                    getPath
                    (
                    )
                    +
                    "\" selected=\"selected\">"
                    +
                    titleCat
                    +
                    "</option>"
                    )
                    ;
                    else
                    out
                    .
                    println
                    (
                    "<option value=\""
                    +
                    cat
                    .
                    getPath
                    (
                    )
                    +
                    "\">"
                    +
                    titleCat
                    +
                    "</option>"
                    )
                    ;
                    }
                %>
            </select>
        </div>
    </c:when>
    <c:when test="${elem.value.FieldType == 'radio' }">
        <div class="form-group" id="filter-${status.count}">
            <div class="radio"><label for="${fieldName}"><input type="radio"
                                                                name="${fieldName}"
                                                                id="${fieldName}"
                                                                value=""
                                                                checked="checked"><fmt:message
                    key="formatter.filter.nocategory"/></label></div>
            <%
                String
                fieldValue
                =
                request
                .
                getParameter
                (
                fieldName
                )
                ;
                // si nos llega el parametro vacio guardamos la propiedad de categoria definida (si es que existe) como fieldvalue para que se muestre seleccionada
                if
                (
                StringUtils
                .
                isBlank
                (
                fieldValue
                )
                )
                {
                fieldValue
                =
                (
                String
                )
                request
                .
                getAttribute
                (
                "filtercategoryProperty"
                )
                ;
                }
                if
                (
                fieldValue
                ==
                null
                )
                fieldValue
                =
                ""
                ;
                if
                (
                tituloCatPadre
                !=
                null
                )
                {
                if
                (
                fieldValue
                .
                equals
                (
                categoryRoot
                )
                )
                out
                .
                println
                (
                "<div class=\"radio\"><label for=\""
                +
                fieldName
                +
                "\"><input type=\"radio\" id=\""
                +
                fieldName
                +
                "\" name=\""
                +
                fieldName
                +
                "\" value=\""
                +
                categoryRoot
                +
                "\" checked=\"checked\">"
                +
                tituloCatPadre
                +
                "</label></div>"
                )
                ;
                else
                out
                .
                println
                (
                "<div class=\"radio\"><label for=\""
                +
                fieldName
                +
                "\"><input type=\"radio\" id=\""
                +
                fieldName
                +
                "\" name=\""
                +
                fieldName
                +
                "\" value=\""
                +
                categoryRoot
                +
                "\">"
                +
                tituloCatPadre
                +
                "</label></div>"
                )
                ;
                }
                for
                (
                CmsCategory
                cat
                :
                categorias
                )
                {
                String
                titleCat
                =
                ""
                ;
                //Primero intentamos leer la categoria Title_LOCALE, si no nos quedamos con el Title
                try
                {
                String
                site
                =
                OpenCms
                .
                getSiteManager
                (
                )
                .
                getCurrentSite
                (
                cmso
                )
                .
                getSiteRoot
                (
                )
                ;
                String
                pathResourceCat
                =
                cat
                .
                getRootPath
                (
                )
                ;
                pathResourceCat
                =
                pathResourceCat
                .
                replace
                (
                site
                ,
                ""
                )
                ;
                titleCat
                =
                cmso
                .
                readPropertyObject
                (
                pathResourceCat
                ,
                "Title_"
                +
                cmso
                .
                getRequestContext
                (
                )
                .
                getLocale
                (
                )
                ,
                false
                )
                .
                getValue
                (
                cat
                .
                getTitle
                (
                )
                )
                ;
                }
                catch
                (
                CmsException
                ex
                )
                {
                titleCat
                =
                cat
                .
                getTitle
                (
                )
                ;
                }
                if
                (
                fieldValue
                .
                equals
                (
                cat
                .
                getPath
                (
                )
                )
                )
                out
                .
                println
                (
                "<div class=\"radio\"><label for=\""
                +
                fieldName
                +
                "\"><input type=\"radio\" id=\""
                +
                fieldName
                +
                "\" name=\""
                +
                fieldName
                +
                "\" value=\""
                +
                cat
                .
                getPath
                (
                )
                +
                "\" checked=\"checked\">"
                +
                titleCat
                +
                "</label></div>"
                )
                ;
                else
                out
                .
                println
                (
                "<div class=\"radio\"><label for=\""
                +
                fieldName
                +
                "\"><input type=\"radio\" id=\""
                +
                fieldName
                +
                "\" name=\""
                +
                fieldName
                +
                "\" value=\""
                +
                cat
                .
                getPath
                (
                )
                +
                "\">"
                +
                titleCat
                +
                "</label></div>"
                )
                ;
                }
            %>
        </div>
    </c:when>
    <c:when test="${elem.value.FieldType == 'checkbox' }">
        <div class="form-group" id="filter-${status.count}">
            <c:set var="fieldName" value="${value.Id }field-${status.count}"/>
            <%
                String
                [
                ]
                fieldValuesArray
                =
                request
                .
                getParameterValues
                (
                fieldName
                )
                ;
                List
                <
                String
                >
                fieldValues
                =
                null
                ;
                // si nos llega el parametro vacio guardamos la propiedad de categoria definida (si es que existe) como fieldvalue para que se muestre seleccionada
                String
                categoryProperty
                =
                (
                String
                )
                request
                .
                getAttribute
                (
                "filtercategoryProperty"
                )
                ;

                if
                (
                fieldValuesArray
                !=
                null
                )
                fieldValues
                =
                Arrays
                .
                asList
                (
                fieldValuesArray
                )
                ;
                else
                if
                (
                !
                StringUtils
                .
                isBlank
                (
                categoryProperty
                )
                )
                {
                fieldValues
                =
                new
                ArrayList
                <
                String
                >
                (
                )
                ;
                fieldValues
                .
                add
                (
                categoryProperty
                )
                ;
                }
                else
                fieldValues
                =
                new
                ArrayList
                <
                String
                >
                (
                )
                ;
                if
                (
                tituloCatPadre
                !=
                null
                )
                {
                if
                (
                fieldValues
                .
                contains
                (
                categoryRoot
                )
                )
                out
                .
                println
                (
                "<div class=\"checkbox\"><label for=\""
                +
                fieldName
                +
                "\"><input type=\"checkbox\" id=\""
                +
                fieldName
                +
                "\" name=\""
                +
                fieldName
                +
                "\" value=\""
                +
                categoryRoot
                +
                "\" checked=\"checked\">"
                +
                tituloCatPadre
                +
                "</label></div>"
                )
                ;
                else
                out
                .
                println
                (
                "<div class=\"checkbox\"><label for=\""
                +
                fieldName
                +
                "\"><input type=\"checkbox\" id=\""
                +
                fieldName
                +
                "\" name=\""
                +
                fieldName
                +
                "\" value=\""
                +
                categoryRoot
                +
                "\">"
                +
                tituloCatPadre
                +
                "</label></div>"
                )
                ;
                }
                for
                (
                CmsCategory
                cat
                :
                categorias
                )
                {
                String
                titleCat
                =
                ""
                ;
                //Primero intentamos leer la categoria Title_LOCALE, si no nos quedamos con el Title
                try
                {
                String
                site
                =
                OpenCms
                .
                getSiteManager
                (
                )
                .
                getCurrentSite
                (
                cmso
                )
                .
                getSiteRoot
                (
                )
                ;
                String
                pathResourceCat
                =
                cat
                .
                getRootPath
                (
                )
                ;
                pathResourceCat
                =
                pathResourceCat
                .
                replace
                (
                site
                ,
                ""
                )
                ;
                titleCat
                =
                cmso
                .
                readPropertyObject
                (
                pathResourceCat
                ,
                "Title_"
                +
                cmso
                .
                getRequestContext
                (
                )
                .
                getLocale
                (
                )
                ,
                false
                )
                .
                getValue
                (
                cat
                .
                getTitle
                (
                )
                )
                ;
                }
                catch
                (
                CmsException
                ex
                )
                {
                titleCat
                =
                cat
                .
                getTitle
                (
                )
                ;
                }
                if
                (
                fieldValues
                .
                contains
                (
                cat
                .
                getPath
                (
                )
                )
                )
                out
                .
                println
                (
                "<div class=\"checkbox\"><label for=\""
                +
                fieldName
                +
                "\"><input type=\"checkbox\" id=\""
                +
                fieldName
                +
                "\" name=\""
                +
                fieldName
                +
                "\" value=\""
                +
                cat
                .
                getPath
                (
                )
                +
                "\" checked=\"checked\">"
                +
                titleCat
                +
                "</label></div>"
                )
                ;
                else
                out
                .
                println
                (
                "<div class=\"checkbox\"><label for=\""
                +
                fieldName
                +
                "\"><input type=\"checkbox\" id=\""
                +
                fieldName
                +
                "\" name=\""
                +
                fieldName
                +
                "\" value=\""
                +
                cat
                .
                getPath
                (
                )
                +
                "\">"
                +
                titleCat
                +
                "</label></div>"
                )
                ;
                }
            %>
        </div>
    </c:when>
    </c:choose>--%>
</div>